codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: 'header,diff,files,footer'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - 'node_modules/**'
  - 'build/**'
  - 'coverage/**'
  - '__test__/**'
  - '*.test.js'
  - '*.test.ts'
  - 'jest.config.js'
  - 'tsconfig*.json'
  - '.github/**'
  - '.prettierrc'
  - '.prettierignore'
  - 'audit-ci.json'
